{% if nodes['type.web.containerization.docker'] %}
FROM composer:latest as composer

WORKDIR /home/app

COPY ./composer.json /home/app
COPY ./composer.lock /home/app

RUN composer install \
    --ignore-platform-reqs \
    --no-interaction \
    --no-plugins \
    --no-scripts \
    --no-dev

FROM php:{{ nodes['phpVersion'].description }}-fpm-alpine

WORKDIR /home/app

COPY --from=composer /usr/bin/composer /usr/local/bin/composer
COPY --from=composer /home/app/vendor /home/app/vendor
COPY . /home/app

RUN composer install --no-interaction --no-dev

EXPOSE 80
{% endif %}
