FROM php:8.0-cli-alpine

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN install-php-extensions yaml

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

RUN apk --update add ncurses

WORKDIR /home/phpxc

RUN composer global require lsbproject/phpxc
ENV PATH /root/.composer/vendor/bin:$PATH

ENTRYPOINT ["phpxc"]
