{% if nodes['type.web.containerization.docker'] %}
FROM {{ nodes['name'].text }}

COPY docker/dev/docker-entrypoint.sh /usr/local/bin/docker-entrypoint
RUN chmod +x /usr/local/bin/docker-entrypoint
{% if nodes['type.web.containerization.docker.storage'] %}

COPY docker/dev/wait-for-it.sh /usr/local/bin/wait-for-it
RUN chmod +x /usr/local/bin/wait-for-it
{% endif %}

RUN apk --update --no-cache add autoconf g++ make bash && \
    pecl install -f xdebug && \
    docker-php-ext-enable xdebug && \
    apk del --purge autoconf g++ make

ENV XDEBUG_HOST='docker.for.mac.localhost'
ENV XDEBUG_IDEKEY='Docker'
ENV XDEBUG_PATH=/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

# Enable Remote xdebug
RUN echo "memory_limit=-1" >> /usr/local/etc/php/php.ini && \
    echo "xdebug.xdebug.mode = develop" >> ${XDEBUG_PATH} && \
    echo "xdebug.idekey = ${XDEBUG_IDEKEY}" >> ${XDEBUG_PATH} && \
    echo "xdebug.start_with_request=yes" >> ${XDEBUG_PATH} && \
    echo "xdebug.discover_client_host = 0" >> ${XDEBUG_PATH} && \
    echo "xdebug.mode = debug" >> ${XDEBUG_PATH} && \
    echo "xdebug.client_host = ${XDEBUG_HOST}" >> ${XDEBUG_PATH}

RUN composer install

ENTRYPOINT docker-entrypoint
{% endif %}
