services:
    LSBProject\PHPXC\Application\Console\Command\Create:
        class: LSBProject\PHPXC\Application\Console\Command\Create
        arguments:
            - '@LSBProject\PHPXC\Application\Console\PathResolver'
            - '@LSBProject\PHPXC\Domain\ShellTemplateBuilder'
            - '@LSBProject\PHPXC\Application\Console\Configuration\Validator'

    LSBProject\PHPXC\Application\Console\Command\Config\Validate:
        class: LSBProject\PHPXC\Application\Console\Command\Config\Validate
        arguments:
            - '@LSBProject\PHPXC\Application\Console\PathResolver'
            - '@LSBProject\PHPXC\Application\Console\Configuration\Validator'

    LSBProject\PHPXC\Application\Console\Command\Config\Show:
        class: LSBProject\PHPXC\Application\Console\Command\Config\Show
        arguments:
            - '@LSBProject\PHPXC\Application\Console\PathResolver'

    LSBProject\PHPXC\Application\Console\PathResolver:
        class: LSBProject\PHPXC\Application\Console\PathResolver
        arguments:
            - '@LSBProject\PHPXC\Infrastructure\Filesystem'
            - '@LSBProject\PHPXC\Infrastructure\Git'

    LSBProject\PHPXC\Domain\ShellTemplateBuilder:
        class: LSBProject\PHPXC\Domain\ShellTemplateBuilder
        arguments:
            - '@LSBProject\PHPXC\Domain\TemplateBuilder'
            - '@LSBProject\PHPXC\Domain\Contract\ShellExecutorInterface'

    LSBProject\PHPXC\Domain\TemplateBuilder:
        class: LSBProject\PHPXC\Domain\TemplateBuilder
        arguments:
            - '@LSBProject\PHPXC\Domain\Contract\FilesystemInterface'
            - '@LSBProject\PHPXC\Domain\Contract\TemplateEngineInterface'

    LSBProject\PHPXC\Application\Console\Configuration\Validator:
        class: LSBProject\PHPXC\Application\Console\Configuration\Validator

    LSBProject\PHPXC\Infrastructure\Filesystem:
        class: LSBProject\PHPXC\Infrastructure\Filesystem

    LSBProject\PHPXC\Domain\Contract\FilesystemInterface: '@LSBProject\PHPXC\Infrastructure\Filesystem'

    LSBProject\PHPXC\Domain\Contract\TemplateEngineInterface:
        class: LSBProject\PHPXC\Infrastructure\TwigTemplateEngine

    LSBProject\PHPXC\Domain\Contract\ShellExecutorInterface:
        class: LSBProject\PHPXC\Infrastructure\ShellExecutor

    CzProject\GitPhp\Git:
        class: CzProject\GitPhp\Git

    LSBProject\PHPXC\Infrastructure\Git:
        class: LSBProject\PHPXC\Infrastructure\Git
        arguments:
            - '@CzProject\GitPhp\Git'
