name: CI
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
              php-version: '8'
              tools: composer

        - name: Install dependencies
          run: composer install && composer require --dev lsbproject/php-clean-code-rules

        - name: Run linter
          run: composer run lint

        - name: Run analyze
          run: composer run analyzer
