name: CI
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
              php-version: '8'
              tools: composer

        - name: Install dependencies
          run: composer install

        - name: Run linter
          run: composer run lint

        - name: Run analyzer
          run: composer run analyze
