name: CI
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
              php-version: '8'
              tools: composer

        - name: Install dependencies
          uses: php-actions/composer@v5

        - name: Run PHPSTAN
          uses: php-actions/phpstan@v2

        - name: Run linter
          run: composer run lint
